# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-09 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pila', '0003_auto_20161031_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('operador_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pila.OperadorServicio')),
            ],
        ),
        migrations.AlterField(
            model_name='novedad',
            name='pensionado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pila.Pensionado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pila.Pensionado'),
        ),
    ]
