# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-25 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pila', '0004_auto_20161108_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNovedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPagadorPensiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPensionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPensionadoTipoPagadorPensiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pagador_pensiones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pila.TipoPagadorPensiones')),
                ('tipo_pensionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pila.TipoPensionado')),
            ],
        ),
        migrations.AddField(
            model_name='pensionado',
            name='tipo_pension',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aportante',
            name='tipo_pagador_pensiones',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='tipo_novedad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pensionado',
            name='residencia_exterior',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pensionado',
            name='tipo_pensionado',
            field=models.IntegerField(),
        ),
    ]
